articles/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views
app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article),
    # url(r'^(?P<slugs>[\w-]+)/$', views.article_detail, name='detail')
    path('<slug:slugs>', views.article_detail, name='detail')
]

jango/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^$', views.index, name='index'),
    url(r'^articles/', include('articles.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^user/', include('users.urls'))
]

products/urls.py
from django.conf.urls import url
from django.urls import path, re_path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.products),
    path('add-prod/', views.addProd)
]

users/urls.py
from django.urls import path
from . import views


urlpatterns= [
    path('register/', views.register)
]

articles/models.py
from django.db import models
from djongo import models

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(max_length=40, default=None)
    description = models.TextField()


    def __str__(this):
        return this.title

    def excerpt(this):
        return this.description[: 8]

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    prodtitle = models.TextField(max_length=30)
    photo = models.ImageField(default='default.png')

    def __str__(self):
        return self.prodtitle

users/models.py
from django.db import models

# Create your models here.

articles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Articles
# Create your views here.
def article(request):
    # ORM
    article = Articles.objects.all()

    # RAW SQL
    # article  = Articles.objects.raw('select * from articles_articles')

    return render(request, 'article/article.html', {'articles': article})
    # return HttpResponse('aws')

def article_detail(request, slugs):
    article = Articles.objects.get(slug=slugs)
    # return HttpResponse(slug)
    return render(request, 'article/article_detail.html', { 'articles': article })

jango/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

products/controller.py
from .models import Product

class ProductController:

    def get_products():
        return Product.objects.all()

    def addProduct():
        return Product(prodtitle = 'product 2').save()
        # print(self.prod)

        # self.prod.prodtitle = params['prodtitle']
        # return self.prod
        # self.save()

products/views.py
from django.shortcuts import render
from django.http import HttpResponse
# from .models import Product
from .controller import ProductController


# Create your views here.
def products(request):
    product = ProductController.get_products()
    return render(request, 'products/products.html', {'products': product})

def addProd(request):
    product = ProductController.addProduct()
    return HttpResponse(product)

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/admin')
    else:
        userForm = UserCreationForm()
        return render(request, 'register.html', {'userForm': userForm})

articles/templates/article/article.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <div>
        <img src="{% static 'images.png'%}" alt="" />
        {% for article in articles %}
            <p>
                <a href="{% url 'articles:detail' slugs=article.slug %}">{{article}}</a>
            </p>
            <p>
                {{article.excerpt | default:'taeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'}}
            </p>
        {% endfor %}
    </div>
{% endblock %}

articles/templates/article/article_detail.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <div>
        <img src="{% static 'images.png'%}" alt="" />
        <p>{{articles.title}}</p>
        <p>{{articles.description}}</p>
    </div>
{% endblock %}

products/templates/products/products.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
    <p> taeeeeeee </p>
    <p>{{ products }}</p>
{% endblock %}

templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body>
    {% block content %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base_template.html' %}

{% block content %}
    <div>
        <p>
            index
        </p>
    </div>
{% endblock %}

users/templates/register.html
{% extends 'base_template.html' %}

{% block content %}
<form action="/user/register/" method="post">
    {% csrf_token %}
    {{userForm}}
    <input type="submit" class="btn btn-primary" value="Register">
</form>
{% endblock %}